Repository scaleway-terraform-modules/terraform-scaleway-bucket, pull requests merged in 2025-03, with the labels that each got.

#55 fix: correct policy schema
  README.md
  variables.tf
Labels: bug, good first issue

#56 fix: actually correct policy schema
  README.md
  variables.tf
Labels: bug

#57 fix: versioning_enabled=true logic
  README.md
  main.tf
  variables.tf
Labels: bug

#59 fix: Repair version suspending
  README.md
  main.tf
  variables.tf
Labels: bug, documentation

#60 Allow wildcard in principal policy definition
  README.md
Labels: bug, documentation
